language: go

sudo: false

go: master

before_install:
  - go get github.com/WindomZ/testify/assert
  - go get github.com/mattn/goveralls

script:
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -ignore="main.go" -service=travis-ci
  - go test -v ./...
